CREATE TABLE mountains(
id INT AUTO_INCREMENT UNIQUE PRIMARY KEY,
name VARCHAR(50)
);

CREATE TABLE peaks(
id INT AUTO_INCREMENT UNIQUE PRIMARY KEY,
name VARCHAR(50),
mountain_id INT
);

ALTER TABLE peaks
ADD CONSTRAINT fk_mountain_id FOREIGN KEY (mountain_id) REFERENCES mountains(id);